//! The Claude CLI sessions running on this machine — read-only.
//!
//! This is hub's OTHER job, and the one the owner actually asked for: he runs
//! `claude` in terminals on this Mac and wants to watch and drive that work
//! from a phone. Everything here observes; nothing here starts, stops, or types
//! into a session. Driving comes later and will be its own module, because a
//! read-only view can ship (and be trusted) on its own.
//!
//! Three facts about this machine decided the shape, all measured 2026-08-08:
//!
//!   1. `claude agents --json` lists live sessions WITHOUT needing a TTY, but
//!      only for one account: acc1 had 9, acc2 had 2, acc3 had 3. An account is
//!      selected by `CLAUDE_CONFIG_DIR`, and the default account is selected by
//!      that variable being ABSENT — pointing it at `~/.claude` reports "not
//!      logged in". So: one call per account, and the default account's entry
//!      must clear the variable rather than set it.
//!   2. Transcripts live at `<transcript_root>/projects/<slug>/<id>.jsonl` and
//!      are appended live. On this machine acc2/acc3 symlink `projects` back to
//!      acc1, so one root covers all three.
//!   3. `cwd` is NOT the project: all 14 live sessions were started from
//!      `~/Documents/projects`, the parent folder. The session NAME is what
//!      carries meaning ("Tiếp tục dwork"), and `projects-87` is autogenerated.

use std::collections::BTreeMap;
use std::io::{Read, Seek, SeekFrom};
use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::Result;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use crate::config::{ClaudeAccountCfg, Config};
use crate::exec::{run, truncate, RunOpts};
use crate::logging;

/// How much of the tail of a transcript to read. Transcripts reach 12 MB; the
/// last conversational turn is always within a few hundred KB of the end, and
/// reading the whole file 14 times per cycle would be the expensive way to
/// learn the same thing.
const TAIL_BYTES: u64 = 256 * 1024;
const PREVIEW_CHARS: usize = 240;
const LIST_TIMEOUT: Duration = Duration::from_secs(30);

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LiveSession {
    /// Which account owns it — the label from config, not a credential.
    pub account: String,
    pub session_id: String,
    /// Autogenerated ("projects-87") or meaningful ("Tiếp tục dwork").
    pub name: String,
    pub cwd: String,
    /// "interactive" (a terminal / editor) or "background".
    pub kind: String,
    pub pid: i64,
    pub started_at_ms: i64,
    /// Last write to the transcript, RFC3339. `None` = no transcript found.
    pub last_activity: Option<String>,
    /// Role of the last real conversation turn, skipping bookkeeping records.
    pub last_role: Option<String>,
    pub last_text: Option<String>,
    /// Why this row is thinner than the others. Never silently empty.
    pub note: Option<String>,
    /// Whether the agent is working right now ("busy") or waiting ("idle"), and
    /// whether it finished ("done"). Both come straight from `claude agents`,
    /// and both are **absent for interactive sessions** — measured 2026-08-08,
    /// only background rows carry them. An empty pair therefore means "hub
    /// cannot tell", never "the session is idle".
    ///
    /// It is also the only honest answer hub has to "is it still working?":
    /// the transcript records neither a cost nor a completion marker.
    pub status: Option<String>,
    pub state: Option<String>,
    /// The permission mode the session is running under ("auto", "dontAsk",
    /// "default"…).
    ///
    /// Measured 2026-08-08 across ~14k records: the transcript records the
    /// MODE and never an individual pending prompt, and every session here runs
    /// `auto` (648) or `dontAsk` (76) — they do not ask. So "show me when it
    /// asks for permission" has nothing to show; what matters on a phone is
    /// knowing a session is running unattended in the first place.
    pub permission_mode: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SessionsSnapshot {
    pub sessions: Vec<LiveSession>,
    /// Per-account problems: CLI missing, not logged in, unparseable output.
    /// An account that failed must not look like an account with no sessions.
    pub notes: Vec<String>,
}

/// `~/Documents/projects` → `-Users-hanguyen-Documents-projects`.
///
/// The rule the CLI uses for its transcript folders: every path separator
/// becomes a dash, including the leading one.
pub fn transcript_slug(cwd: &str) -> String {
    let trimmed = cwd.trim_end_matches('/');
    if trimmed.is_empty() {
        return "-".to_string();
    }
    trimmed.replace('/', "-")
}

pub fn transcript_path(root: &Path, cwd: &str, session_id: &str) -> PathBuf {
    root.join("projects")
        .join(transcript_slug(cwd))
        .join(format!("{session_id}.jsonl"))
}

/// Records that are bookkeeping, not conversation. Observed on real
/// transcripts: `pr-link`, `attachment`, `system`, `last-prompt`,
/// `file-history-snapshot`, `queue-operation`, `ai-title`, `mode`,
/// `permission-mode`. Reading the LAST record and calling it the state gets the
/// answer wrong for 5 of 14 live sessions, which is why this walks backwards.
fn is_conversation(kind: &str) -> bool {
    matches!(kind, "assistant" | "user")
}

/// Plain text out of a message record, whatever shape it arrived in.
fn text_of(record: &Value) -> Option<String> {
    let content = record.get("message")?.get("content")?;
    if let Some(s) = content.as_str() {
        return Some(s.trim().to_string()).filter(|s| !s.is_empty());
    }
    let joined = content
        .as_array()?
        .iter()
        .filter_map(|block| match block.get("type").and_then(|t| t.as_str()) {
            Some("text") => block
                .get("text")
                .and_then(|t| t.as_str())
                .map(str::to_string),
            // A turn that is only tool calls has no text; say what it was doing
            // rather than showing an empty row.
            Some("tool_use") => block
                .get("name")
                .and_then(|n| n.as_str())
                .map(|n| format!("[dùng {n}]")),
            _ => None,
        })
        .collect::<Vec<_>>()
        .join(" ");
    Some(joined.trim().to_string()).filter(|s| !s.is_empty())
}

/// Leak labels that make a preview unsafe to carry off this machine.
///
/// NOT the whole of `redaction::leak_scan`. That gate is tuned for a reply to
/// an outsider, so it also flags `/Users/…` paths, IP addresses and words like
/// "blocker" — true of nearly every line of a development session, which would
/// blank the whole view and teach the owner to ignore it. These three are the
/// ones where being wrong is unrecoverable.
///
/// Not hypothetical: the first real run of `hub sessions` (2026-08-08) printed
/// a session whose latest turn stated a login password in plain text. The CLI
/// runs on the owner's own machine, so that is his business — but the portal
/// snapshot lands in a tfl5 doc on a server, which `redaction.rs` itself counts
/// as leaving the machine.
const SECRET_LABELS: [&str; 4] = [
    "credential_word",
    "credential_word_vi",
    "credential_literal",
    "private_key_block",
];

/// Tools a session hub starts (`/new`) or continues (`/tell`) may never reach.
///
/// Lived in `act.rs` until 2026-08-08; that module was the inbox's "implement
/// the approved change" branch and went with the inbox, but the list itself is
/// a structural wall, not part of that product: a phone types one sentence and
/// a process with the owner's own shell runs unattended on the other end. Deny
/// what cannot be taken back — push/merge/reset rewrite shared history, ssh /
/// scp / rsync / sudo / rm / docker / launchctl / *deploy* reach past this
/// machine or destroy on it, and WebFetch/WebSearch turn a task into a channel
/// out. Writes inside the working tree stay allowed: that is the work.
pub const DENIED_TOOLS: [&str; 17] = [
    "Bash(git push:*)",
    "Bash(git merge:*)",
    "Bash(git rebase:*)",
    "Bash(git reset:*)",
    "Bash(ssh:*)",
    "Bash(scp:*)",
    "Bash(rsync:*)",
    "Bash(sudo:*)",
    "Bash(rm:*)",
    "Bash(curl:*)",
    "Bash(wget:*)",
    "Bash(psql:*)",
    "Bash(docker:*)",
    "Bash(launchctl:*)",
    "Bash(*deploy*)",
    "WebFetch",
    "WebSearch",
];

/// Hits that must suppress a preview, or empty if it is safe to carry.
pub fn preview_risk(text: &str) -> Vec<String> {
    crate::redaction::leak_scan(text, &[])
        .into_iter()
        .filter(|l| SECRET_LABELS.contains(&l.as_str()))
        .collect()
}

#[derive(Debug, Default, PartialEq)]
pub struct TranscriptTail {
    pub last_role: Option<String>,
    pub last_text: Option<String>,
    /// Timestamp carried by the last conversational record, if it has one.
    pub last_ts: Option<String>,
    /// Newest `permission-mode` seen in the window.
    pub permission_mode: Option<String>,
}

/// Walk the tail backwards to the newest real conversation turn.
pub fn parse_tail(tail: &str) -> TranscriptTail {
    let mut out = TranscriptTail::default();
    for line in tail.lines().rev() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let Ok(record) = serde_json::from_str::<Value>(line) else {
            // A partial first line is expected: the tail starts mid-file.
            continue;
        };
        let kind = record.get("type").and_then(|t| t.as_str()).unwrap_or("");
        if kind == "permission-mode" && out.permission_mode.is_none() {
            out.permission_mode = record
                .get("permissionMode")
                .and_then(|m| m.as_str())
                .map(str::to_string);
        }
        if !is_conversation(kind) {
            continue;
        }
        // Newest wins: keep scanning backwards only for what is still missing,
        // never overwrite a turn already found with an older one.
        if out.last_text.is_some() {
            continue;
        }
        out.last_role = record
            .get("message")
            .and_then(|m| m.get("role"))
            .and_then(|r| r.as_str())
            .map(str::to_string)
            .or_else(|| Some(kind.to_string()));
        out.last_text = text_of(&record).map(|t| truncate(&t, PREVIEW_CHARS));
        out.last_ts = record
            .get("timestamp")
            .and_then(|t| t.as_str())
            .map(str::to_string);
        // Stop once BOTH are known: the newest turn and the mode it runs under.
        if out.last_text.is_some() && out.permission_mode.is_some() {
            break;
        }
    }
    out
}

fn read_tail(path: &Path) -> Result<String> {
    let mut file = std::fs::File::open(path)?;
    let len = file.metadata()?.len();
    if len > TAIL_BYTES {
        file.seek(SeekFrom::Start(len - TAIL_BYTES))?;
    }
    let mut buf = Vec::with_capacity(TAIL_BYTES as usize);
    file.read_to_end(&mut buf)?;
    Ok(String::from_utf8_lossy(&buf).to_string())
}

fn mtime_rfc3339(path: &Path) -> Option<String> {
    let modified = std::fs::metadata(path).ok()?.modified().ok()?;
    let ts: chrono::DateTime<chrono::Utc> = modified.into();
    Some(ts.to_rfc3339_opts(chrono::SecondsFormat::Secs, true))
}

/// Ask one account's CLI what it has running.
fn list_account(account: &ClaudeAccountCfg, cli: &str) -> Result<Vec<Value>> {
    // Absent variable = default account. Setting it to ~/.claude reports "not
    // logged in", so the default account MUST clear it, not point at it.
    let env = vec![(
        "CLAUDE_CONFIG_DIR".to_string(),
        account
            .config_dir
            .as_deref()
            .filter(|d| !d.is_empty())
            .map(|d| {
                crate::config::expand_home(Path::new(d))
                    .to_string_lossy()
                    .to_string()
            }),
    )];
    let out = run(
        cli,
        &["agents", "--json"],
        RunOpts {
            timeout: Some(LIST_TIMEOUT),
            env,
            ..Default::default()
        },
    )?;
    if out.timed_out {
        anyhow::bail!("`{cli} agents --json` timed out after {}ms", out.ms);
    }
    if out.code != Some(0) {
        anyhow::bail!(
            "`{cli} agents --json` exit {:?}: {}",
            out.code,
            truncate(
                if out.stderr.trim().is_empty() {
                    &out.stdout
                } else {
                    &out.stderr
                },
                200
            )
        );
    }
    let value: Value = serde_json::from_str(&out.stdout).map_err(|e| {
        anyhow::anyhow!("unparseable JSON: {e}; head={}", truncate(&out.stdout, 200))
    })?;
    Ok(value.as_array().cloned().unwrap_or_default())
}

/// Every live session across every configured account, newest activity first.
pub fn snapshot(cfg: &Config) -> SessionsSnapshot {
    let mut out = SessionsSnapshot::default();
    let root = cfg.claude_transcript_root();

    for account in &cfg.claude_accounts_or_ambient() {
        let raw = match list_account(account, &cfg.claude_cli) {
            Ok(v) => v,
            Err(e) => {
                // An account that failed to answer is NOT an account with zero
                // sessions, and the difference matters on a phone.
                logging::warn(
                    "claude_agents_list_failed",
                    json!({ "account": account.name, "err": e.to_string() }),
                );
                out.notes.push(format!(
                    "{}: {}",
                    account.name,
                    truncate(&e.to_string(), 200)
                ));
                continue;
            }
        };

        for s in raw {
            let cwd = s
                .get("cwd")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string();
            let session_id = s
                .get("sessionId")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string();
            let mut row = LiveSession {
                account: account.name.clone(),
                name: s
                    .get("name")
                    .and_then(|v| v.as_str())
                    .unwrap_or("(không tên)")
                    .to_string(),
                kind: s
                    .get("kind")
                    .and_then(|v| v.as_str())
                    .unwrap_or("unknown")
                    .to_string(),
                pid: s.get("pid").and_then(|v| v.as_i64()).unwrap_or(0),
                started_at_ms: s.get("startedAt").and_then(|v| v.as_i64()).unwrap_or(0),
                status: s.get("status").and_then(|v| v.as_str()).map(str::to_string),
                state: s.get("state").and_then(|v| v.as_str()).map(str::to_string),
                last_activity: None,
                last_role: None,
                last_text: None,
                note: None,
                permission_mode: None,
                cwd: cwd.clone(),
                session_id: session_id.clone(),
            };

            if session_id.is_empty() {
                row.note = Some("phiên không có sessionId".into());
                out.sessions.push(row);
                continue;
            }

            let path = transcript_path(&root, &cwd, &session_id);
            if !path.exists() {
                // Seen for real: 1 of 14 sessions had no transcript yet.
                row.note = Some("chưa có nhật ký phiên".into());
                out.sessions.push(row);
                continue;
            }
            row.last_activity = mtime_rfc3339(&path);
            match read_tail(&path) {
                Ok(tail) => {
                    let parsed = parse_tail(&tail);
                    if parsed.last_text.is_none() {
                        row.note = Some("chưa có lượt hội thoại nào đọc được".into());
                    }
                    if let Some(ts) = parsed.last_ts {
                        row.last_activity = Some(ts);
                    }
                    row.permission_mode = parsed.permission_mode.clone();
                    row.last_role = parsed.last_role;
                    // Suppressed HERE, at the source, so no downstream surface
                    // can forget: the snapshot, the portal doc and the phone
                    // all read this struct.
                    row.last_text = match &parsed.last_text {
                        Some(t) => {
                            let risk = preview_risk(t);
                            if risk.is_empty() {
                                parsed.last_text.clone()
                            } else {
                                row.note = Some(format!(
                                    "ẩn phần xem trước: có thể chứa bí mật ({}) — mở phiên trên máy để xem",
                                    risk.join(", ")
                                ));
                                None
                            }
                        }
                        None => None,
                    };
                }
                Err(e) => {
                    logging::warn(
                        "claude_transcript_read_failed",
                        json!({ "path": path.display().to_string(), "err": e.to_string() }),
                    );
                    row.note = Some(format!(
                        "không đọc được nhật ký: {}",
                        truncate(&e.to_string(), 120)
                    ));
                }
            }
            out.sessions.push(row);
        }
    }

    // Newest first: half the live sessions had not moved in 40 hours, so a flat
    // list buries the one being worked on right now.
    out.sessions.sort_by(|a, b| {
        b.last_activity
            .cmp(&a.last_activity)
            .then_with(|| b.started_at_ms.cmp(&a.started_at_ms))
    });
    out
}

/// One thing that happened in a session, in the order it happened.
///
/// This is the unit the phone renders to look like a terminal: a sentence, a
/// command, a command's output, a thought. `kind` is what it was, `text` is
/// what to show, `detail` is the extra line a command needs (its arguments).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct StreamEvent {
    /// "say" · "tool" · "result" · "think"
    pub kind: String,
    /// "user" | "assistant"
    pub role: String,
    pub ts: Option<String>,
    /// Tool name for `tool`, empty otherwise.
    pub name: String,
    pub text: String,
    /// True when the leak gate replaced the text — never a silent blank.
    pub withheld: bool,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SessionStream {
    pub session_id: String,
    pub events: Vec<StreamEvent>,
    /// Events dropped off the front because the window is bounded.
    pub older_hidden: usize,
    pub note: Option<String>,
}

/// How much of a tool's output to carry. A `Bash` result can be a whole test
/// run; the phone needs the shape of it, not all of it.
const RESULT_CHARS: usize = 700;
const SAY_CHARS: usize = 4000;

fn block_text(block: &Value) -> String {
    match block.get("type").and_then(|t| t.as_str()) {
        Some("text") => block
            .get("text")
            .and_then(|t| t.as_str())
            .unwrap_or_default()
            .to_string(),
        Some("thinking") => block
            .get("thinking")
            .and_then(|t| t.as_str())
            .unwrap_or_default()
            .to_string(),
        Some("tool_use") => {
            let input = block
                .get("input")
                .map(|i| i.to_string())
                .unwrap_or_default();
            input
        }
        Some("tool_result") => match block.get("content") {
            Some(Value::String(s)) => s.clone(),
            Some(Value::Array(items)) => items
                .iter()
                .filter_map(|b| b.get("text").and_then(|t| t.as_str()))
                .collect::<Vec<_>>()
                .join("\n"),
            _ => String::new(),
        },
        _ => String::new(),
    }
}

/// Every block becomes an event, and every event passes the leak gate on its
/// OWN text.
///
/// This is where "show it like the terminal" collides with "do not publish
/// secrets": a `tool_result` is the output of a command, which is exactly
/// where keys and env vars surface. Gating only the last turn (what the list
/// screen does) would be useless here.
pub fn parse_stream(tail: &str, limit: usize) -> SessionStream {
    let mut events: Vec<StreamEvent> = vec![];
    for line in tail.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        // The window starts mid-file, so a partial first line is expected.
        let Ok(record) = serde_json::from_str::<Value>(line) else {
            continue;
        };
        let kind = record.get("type").and_then(|t| t.as_str()).unwrap_or("");
        if !is_conversation(kind) {
            continue;
        }
        let ts = record
            .get("timestamp")
            .and_then(|t| t.as_str())
            .map(str::to_string);
        let role = record
            .get("message")
            .and_then(|m| m.get("role"))
            .and_then(|r| r.as_str())
            .unwrap_or(kind)
            .to_string();
        let Some(content) = record.get("message").and_then(|m| m.get("content")) else {
            continue;
        };

        let blocks: Vec<Value> = match content {
            Value::String(s) => vec![json!({ "type": "text", "text": s })],
            Value::Array(a) => a.clone(),
            _ => vec![],
        };

        for block in blocks {
            let (event_kind, name, cap) = match block.get("type").and_then(|t| t.as_str()) {
                Some("text") => ("say", String::new(), SAY_CHARS),
                Some("thinking") => ("think", String::new(), RESULT_CHARS),
                Some("tool_use") => (
                    "tool",
                    block
                        .get("name")
                        .and_then(|n| n.as_str())
                        .unwrap_or("?")
                        .to_string(),
                    RESULT_CHARS,
                ),
                Some("tool_result") => ("result", String::new(), RESULT_CHARS),
                _ => continue,
            };
            let raw = block_text(&block);
            let raw = raw.trim();
            if raw.is_empty() {
                continue;
            }
            let risk = preview_risk(raw);
            events.push(StreamEvent {
                kind: event_kind.to_string(),
                role: role.clone(),
                ts: ts.clone(),
                name,
                text: if risk.is_empty() {
                    truncate(raw, cap)
                } else {
                    format!("[hub ẩn: có thể chứa bí mật ({})]", risk.join(", "))
                },
                withheld: !risk.is_empty(),
            });
        }
    }

    let older_hidden = events.len().saturating_sub(limit);
    if older_hidden > 0 {
        events.drain(..older_hidden);
    }
    SessionStream {
        session_id: String::new(),
        events,
        older_hidden,
        note: None,
    }
}

/// Find a session's transcript without knowing its `cwd`.
///
/// The follow loop only has an id: it must not pay for three `claude agents`
/// calls every couple of seconds just to rebuild a path. Transcript folders are
/// shallow, so one readdir per project folder is cheap — and this also survives
/// a session whose `cwd` the caller got wrong.
pub fn find_transcript(root: &Path, session_id: &str) -> Option<PathBuf> {
    let file = format!("{session_id}.jsonl");
    let projects = root.join("projects");
    let dirs = std::fs::read_dir(&projects).ok()?;
    for entry in dirs.flatten() {
        let candidate = entry.path().join(&file);
        if candidate.exists() {
            return Some(candidate);
        }
    }
    None
}

/// When the transcript last changed — the signal the follow loop watches.
pub fn transcript_mtime(path: &Path) -> Option<std::time::SystemTime> {
    std::fs::metadata(path).ok()?.modified().ok()
}

/// The recent stream of one session, ready to render.
pub fn stream(cfg: &Config, session_id: &str, cwd: &str, limit: usize) -> SessionStream {
    let mut out = SessionStream {
        session_id: session_id.to_string(),
        ..Default::default()
    };
    let root = cfg.claude_transcript_root();
    let by_cwd = transcript_path(&root, cwd, session_id);
    let path = if by_cwd.exists() {
        by_cwd
    } else {
        match find_transcript(&root, session_id) {
            Some(p) => p,
            None => {
                out.note = Some("chưa có nhật ký phiên".into());
                return out;
            }
        }
    };
    match read_tail(&path) {
        Ok(tail) => {
            let parsed = parse_stream(&tail, limit);
            out.events = parsed.events;
            out.older_hidden = parsed.older_hidden;
            if out.events.is_empty() {
                out.note = Some("chưa có lượt hội thoại nào đọc được".into());
            }
        }
        Err(e) => {
            logging::warn(
                "claude_transcript_read_failed",
                json!({ "path": path.display().to_string(), "err": e.to_string() }),
            );
            out.note = Some(format!(
                "không đọc được nhật ký: {}",
                truncate(&e.to_string(), 120)
            ));
        }
    }
    out
}

/// A closing note for a session, plus the id that continues its thread.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Handover {
    pub source_id: String,
    pub source_name: String,
    /// The session that carries the work forward. Different from `source_id`.
    pub new_session_id: String,
    pub checkpoint: String,
    /// What this call cost. Recorded in `spend`, and deliberately NOT published:
    /// the same struct is serialised into the cursor the portal snapshot
    /// carries, so a field left visible here would put a price back on the
    /// phone screen through the back door (2026-08-08).
    #[serde(default, skip_serializing)]
    pub cost_usd: f64,
    pub ts: String,
    /// How to pick the thread up on the machine.
    pub resume_command: String,
}

const HANDOVER_PROMPT: &str = "\
Phiên này sắp được đóng lại để mở một phiên mới làm tiếp. Viết BÀN GIAO ngắn gọn \
bằng tiếng Việt cho người sẽ tiếp quản, đúng 4 mục, không quá 200 từ:\n\
1. Đang làm gì (mục tiêu của phiên)\n\
2. Đã xong tới đâu — nêu file:dòng hoặc lệnh cụ thể, không nói chung chung\n\
3. Đang dở cái gì, kẹt ở đâu\n\
4. Việc kế tiếp nên làm ngay\n\
Chỉ viết bàn giao. Không chạy công cụ, không sửa file.";

/// What a fork opened from the phone is allowed to touch: reading, nothing else.
///
/// Three measurements on 2026-08-08 pinned this exact list, and each one ruled
/// out an option that looked reasonable on paper:
/// - `--tools ""` (no tools at all) FAILS on a session whose history contains
///   tool calls: the model keeps trying to call one and the run comes back
///   `is_error` — *"The model's tool call could not be parsed"*. Every real
///   session here is tool-heavy, so "just take the tools away" is not on offer.
/// - `--disallowedTools` WITHOUT an allowlist still loads the full tool schema.
///   One sentence cost **$0.2185** that way and blew a $0.20 per-call cap.
/// - With this allowlist, a fork asked to enumerate its own tools answers
///   exactly `Glob · Grep · Read`, and the same question costs **$0.0356**.
///
/// So the fence is structural rather than behavioural: a fork opened from a
/// phone has no hand to write with, and no prompt can talk it into growing one.
/// It is also the cost lever — a smaller tool schema is a smaller prompt.
const FORK_TOOLS: &str = "Read,Grep,Glob";

/// One `claude` turn on a FORK of a live session.
///
/// Fork, not resume-in-place, is the whole safety story: the original
/// transcript comes back byte-identical (measured twice — 15222 bytes on the
/// first handover, and 7380 bytes / 10 lines / unchanged mtime on the probe
/// that fixed `FORK_TOOLS`), so nothing done from the phone can damage the
/// thread it is looking at. The answer lands in a NEW session id, which is why
/// callers must present it as an aside instead of filing it under the parent.
struct ForkReply {
    new_session_id: String,
    text: String,
    cost_usd: f64,
}

/// Dollars per megabyte of transcript, measured: a 0.986 MB session cost $1.72
/// to load on 2026-08-08. `--resume` re-reads the whole conversation, so the
/// price tracks the session's LENGTH, not the length of the question.
const USD_PER_MB: f64 = 1.75;

/// What one fork of `session` is expected to cost, from the size of its log.
///
/// Used for the per-call ceiling instead of borrowing triage's flat $0.50. That
/// figure was sized for a chat message and is smaller than the load cost of 13
/// of the 14 sessions live on this machine — and a call killed by its own
/// ceiling is still BILLED, so a flat cap would have meant paying for nothing,
/// repeatedly, on exactly the big sessions worth asking about.
pub fn fork_cost_estimate(cfg: &Config, session: &LiveSession) -> f64 {
    let root = cfg.claude_transcript_root();
    let by_cwd = transcript_path(&root, &session.cwd, &session.session_id);
    let path = if by_cwd.exists() {
        Some(by_cwd)
    } else {
        find_transcript(&root, &session.session_id)
    };
    // No transcript found means no estimate — return 0 so the caller falls back
    // to its floor rather than inventing a ceiling out of a missing file.
    let bytes = path
        .and_then(|p| std::fs::metadata(p).ok())
        .map(|m| m.len())
        .unwrap_or(0);
    (bytes as f64 / 1_000_000.0) * USD_PER_MB
}

fn fork_call(cfg: &Config, session: &LiveSession, prompt: &str) -> Result<ForkReply> {
    // Cap the CALL. `--resume` loads the whole conversation, so one handover on
    // a 986 KB session cost $1.72 on its first real run (2026-08-08) and a day
    // ceiling only refuses the NEXT call.
    //
    // The cap is derived from this session rather than fixed: doubled headroom
    // over the estimate stops a runaway without refusing honest work, and a
    // floor keeps tiny sessions from getting a ceiling of nearly zero.
    let estimate = fork_cost_estimate(cfg, session);
    let cap = (estimate * 2.0).max(cfg.call.max_budget_usd);
    logging::info(
        "fork_call_budget",
        json!({
            "session": session.session_id,
            "estimate_usd": estimate,
            "cap_usd": cap,
        }),
    );
    let per_call = cap.to_string();
    // Pin the working directory to the session's own, so `Read`/`Grep` resolve
    // against the work being asked about rather than wherever `hubd` was
    // started from.
    let cwd = crate::config::expand_home(Path::new(&session.cwd));
    let out = run(
        &cfg.claude_cli,
        &[
            "-p",
            "--resume",
            &session.session_id,
            "--fork-session",
            "--tools",
            FORK_TOOLS,
            "--disable-slash-commands",
            "--strict-mcp-config",
            "--max-budget-usd",
            &per_call,
            "--output-format",
            "json",
        ],
        RunOpts {
            cwd: cwd.is_dir().then_some(cwd.as_path()),
            input: Some(prompt.to_string()),
            timeout: Some(Duration::from_secs(cfg.call.timeout_sec)),
            env: vec![(
                "CLAUDE_CONFIG_DIR".into(),
                account_dir(cfg, &session.account),
            )],
        },
    )?;
    if out.timed_out {
        anyhow::bail!("quá {}s", cfg.call.timeout_sec);
    }
    if out.code != Some(0) {
        anyhow::bail!(
            "claude exit {:?}: {}",
            out.code,
            truncate(
                if out.stderr.trim().is_empty() {
                    &out.stdout
                } else {
                    &out.stderr
                },
                200
            )
        );
    }
    let v: Value = serde_json::from_str(&out.stdout)
        .map_err(|e| anyhow::anyhow!("kết quả không đọc được: {e}"))?;
    let cost_usd = v
        .get("total_cost_usd")
        .and_then(|c| c.as_f64())
        .unwrap_or(0.0);
    // A budget stop or an unparseable tool call comes back with exit 0 and
    // `is_error: true` — and it is BILLED. Reporting that as an answer would
    // put "The model's tool call could not be parsed" on screen as if the
    // session had said it, so fail loudly and let the caller book the cost.
    if v.get("is_error").and_then(Value::as_bool) == Some(true) {
        anyhow::bail!(
            "claude báo lỗi (đã tính ${cost_usd:.4}): {}",
            truncate(
                v.get("result").and_then(|s| s.as_str()).unwrap_or("(rỗng)"),
                200
            )
        );
    }
    let new_id = v
        .get("session_id")
        .and_then(|s| s.as_str())
        .unwrap_or_default()
        .to_string();
    if new_id.is_empty() || new_id == session.session_id {
        // Without a NEW id there is nothing to continue into, and writing back
        // into the live session is exactly what fork exists to avoid.
        anyhow::bail!("không nhận được session id mới (nhận: {new_id:?})");
    }
    Ok(ForkReply {
        new_session_id: new_id,
        text: v
            .get("result")
            .and_then(|s| s.as_str())
            .unwrap_or_default()
            .trim()
            .to_string(),
        cost_usd,
    })
}

/// Ask a session to write its own handover, on a FORK.
pub fn handover(cfg: &Config, session: &LiveSession) -> Result<Handover> {
    let reply = fork_call(cfg, session, HANDOVER_PROMPT)?;
    Ok(Handover {
        source_id: session.session_id.clone(),
        source_name: session.name.clone(),
        new_session_id: reply.new_session_id.clone(),
        // The handover text is a session talking about its own work, so it can
        // quote anything the session saw — same gate as every other preview.
        checkpoint: gate_preview(
            &reply.text,
            "[hub ẩn bàn giao: có thể chứa bí mật — mở phiên trên máy để xem]",
        ),
        cost_usd: reply.cost_usd,
        ts: crate::logging::now_iso(),
        resume_command: format!(
            "cd {} && claude --resume {}",
            session.cwd, reply.new_session_id
        ),
    })
}

/// A question asked ALONGSIDE a running session, and its answer.
///
/// "Alongside" is the product claim and the reason this is not just a chat
/// message: the answer knows everything the session knows up to now, while the
/// session itself gains no turn and loses no time.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Aside {
    pub source_id: String,
    pub source_name: String,
    /// Where the answer actually lives — a fork, never the parent.
    pub new_session_id: String,
    pub question: String,
    pub answer: String,
    /// See `Handover::cost_usd` — recorded, never published.
    #[serde(default, skip_serializing)]
    pub cost_usd: f64,
    pub ts: String,
}

/// Ask a live session a question without touching it (UC-S05b, level 2).
///
/// The question comes from the owner (`parse_command` refuses anyone else), so
/// it is an order, not untrusted content — but the ANSWER can quote anything
/// the session ever read, which is why it goes through the same preview gate as
/// every other screen.
pub fn ask_aside(cfg: &Config, session: &LiveSession, question: &str) -> Result<Aside> {
    let question = question.trim();
    if question.is_empty() {
        anyhow::bail!("chưa có câu hỏi");
    }
    // Say out loud that this is a side question. Without it the fork reads the
    // transcript as "we were in the middle of X" and carries on working —
    // which it cannot do here anyway (read-only tools), so it would just
    // narrate a plan nobody asked for.
    let prompt = format!(
        "Đây là câu hỏi CHEN NGANG từ chủ máy, hỏi qua điện thoại. Bạn đang ở một \
         bản sao (fork) của phiên — phiên gốc vẫn chạy và KHÔNG bị ảnh hưởng.\n\
         Chỉ TRẢ LỜI câu hỏi dựa trên ngữ cảnh phiên; không tiếp tục công việc dở, \
         không đề xuất kế hoạch, không sửa file (bạn chỉ có công cụ đọc).\n\
         Trả lời bằng tiếng Việt, ngắn gọn, đi thẳng vào câu hỏi.\n\n\
         Câu hỏi: {question}"
    );
    let reply = fork_call(cfg, session, &prompt)?;
    Ok(Aside {
        source_id: session.session_id.clone(),
        source_name: session.name.clone(),
        new_session_id: reply.new_session_id,
        question: question.to_string(),
        answer: gate_preview(
            &reply.text,
            "[hub ẩn câu trả lời: có thể chứa bí mật — mở phiên trên máy để xem]",
        ),
        cost_usd: reply.cost_usd,
        ts: crate::logging::now_iso(),
    })
}

/// Show the text, or say why it is hidden — never show it half-redacted and
/// never blank it without a reason.
fn gate_preview(text: &str, hidden: &str) -> String {
    if preview_risk(text).is_empty() {
        text.to_string()
    } else {
        hidden.to_string()
    }
}

/// A session hub started, and how to find it again.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Started {
    pub session_id: String,
    pub project: String,
    pub cwd: String,
    pub task: String,
    pub ts: String,
}

/// The session id out of `claude --bg`'s human-readable output.
///
/// The id is the FIRST token after the marker, not the rest of the line. A
/// session started without a prompt prints
/// `backgrounded · 6514f454 (idle — send a prompt to start)`, and taking the
/// whole tail stored that entire sentence as the session id — after which
/// `/session`, `/ask`, `/tell` and `/stop` all silently failed to match it,
/// while hub reported the session as started. Pure so the shape can be pinned
/// by a test instead of by another live run.
pub fn parse_backgrounded_id(stdout: &str) -> Option<&str> {
    stdout
        .lines()
        .find_map(|l| l.trim().strip_prefix("backgrounded · "))
        .and_then(|s| s.split_whitespace().next())
        .filter(|s| !s.is_empty())
}

/// Start a new background session in a project folder (UC-S06).
///
/// `--bg` returns in about a second with an id and leaves the agent running —
/// measured 2026-08-08: the row shows up in `claude agents` as
/// `kind: "background"`, named after the task, at `permission_mode: "dontAsk"`.
///
/// Two things follow from that last fact and neither is decoration:
/// - It runs UNATTENDED with tools, so it runs behind `DENIED_TOOLS` (above):
///   no push/merge/reset, no ssh/scp/sudo/rm, no curl. The human approval step
///   non-negotiable #1 asks for is the owner typing the task and pressing the
///   button.
/// - hub cannot tell what it costs. The transcript records no price and
///   `claude agents` reports none, so there is nothing to add up. What hub can
///   do is show that it is running and offer a stop — control and visibility
///   instead of a number that would be invented.
pub fn start_background(cfg: &Config, project: &str, dir: &Path, task: &str) -> Result<Started> {
    let task = task.trim();
    if task.is_empty() {
        anyhow::bail!("chưa nói việc cần làm");
    }
    if !dir.is_dir() {
        anyhow::bail!("không thấy thư mục dự án: {}", dir.display());
    }
    // ORDER IS LOad-BEARING and cost a real run to learn. The prompt is
    // POSITIONAL here — `--bg` and `-p` conflict outright ("--print never
    // starts the interactive session that `claude agents` attaches to") — and
    // `--disallowedTools` is VARIADIC, so a prompt placed after it is eaten as
    // one more tool pattern. The first real `/new` did exactly that: the agent
    // came up with no task at all, reporting itself as
    // "idle — send a prompt to start", and hub cheerfully called it started.
    // Prompt first, variadic last.
    let mut args: Vec<&str> = vec!["--bg", task, "--disallowedTools"];
    args.extend_from_slice(&DENIED_TOOLS);

    let out = run(
        &cfg.claude_cli,
        &args,
        RunOpts {
            cwd: Some(dir),
            input: None,
            timeout: Some(Duration::from_secs(120)),
            env: vec![("CLAUDE_CONFIG_DIR".into(), None)],
        },
    )?;
    if out.code != Some(0) {
        anyhow::bail!(
            "claude exit {:?}: {}",
            out.code,
            truncate(
                if out.stderr.trim().is_empty() {
                    &out.stdout
                } else {
                    &out.stderr
                },
                200
            )
        );
    }
    // Human-readable output, not JSON — the id is on the "backgrounded · <id>"
    // line. Parse defensively: a silent miss here would report success while
    // hub has no idea which session it just started (and cannot stop it).
    let short = parse_backgrounded_id(&out.stdout)
        .map(str::to_string)
        .ok_or_else(|| {
            anyhow::anyhow!(
                "không đọc được id phiên nền từ: {}",
                truncate(out.stdout.trim(), 200)
            )
        })?;

    // The short id is a prefix; resolve it to the full one so every other verb
    // (`/session`, `/ask`, `/tell`, `/stop`) has something to match on. The
    // agent takes a moment to register, so retry rather than storing a prefix
    // that nothing will ever match.
    let mut full = None;
    for _ in 0..8 {
        full = snapshot(cfg)
            .sessions
            .into_iter()
            .find(|s| s.session_id.starts_with(&short))
            .map(|s| s.session_id);
        if full.is_some() {
            break;
        }
        std::thread::sleep(Duration::from_secs(1));
    }
    let full = full.unwrap_or_else(|| {
        // Say it rather than quietly handing back a prefix: the session IS
        // running, the owner should know hub lost track of its full id.
        logging::warn(
            "background_session_id_unresolved",
            json!({ "short": short, "effect": "focus cursor holds a prefix; /session may not match" }),
        );
        short.clone()
    });

    // A started session is not a working session. Measured 2026-08-08: a
    // background agent opened in any folder under this workspace comes up
    // `state: "blocked"`, sitting on an interactive dialog —
    //   "2 new MCP servers found in this project. Select any you wish to
    //    enable. … Space to select · Enter to confirm · Esc to reject all"
    // — raised by the workspace's own `.mcp.json` (project-agent, vault). It
    // waits for a keypress that nobody on a phone can give, writes no
    // transcript, and never does the task. `--strict-mcp-config` does not
    // suppress it, nor does `--mcp-config '{"mcpServers":{}}'` (both tried).
    //
    // Reporting "🚀 đã mở phiên" over that would be the exact failure this
    // project keeps writing down: a green message for work that never ran. So
    // look, and if it is stuck, stop it and say what the one-time fix is.
    let mut stuck = false;
    for _ in 0..7 {
        std::thread::sleep(Duration::from_secs(2));
        let Some(row) = snapshot(cfg)
            .sessions
            .into_iter()
            .find(|s| s.session_id == full)
        else {
            continue;
        };
        if row.state.as_deref() == Some("blocked") {
            stuck = true;
            break;
        }
        // Any transcript at all means it got past the dialog and is working.
        if find_transcript(&cfg.claude_transcript_root(), &full).is_some() {
            break;
        }
    }
    if stuck {
        logging::warn(
            "background_session_blocked",
            json!({ "session": full, "cwd": dir.display().to_string(), "cause": "interactive MCP approval dialog" }),
        );
        // Leave nothing hanging: a blocked agent does no work and only clutters
        // the list the owner is trying to read.
        if let Ok(out) = run(
            &cfg.claude_cli,
            &["stop", short_id(&full)],
            RunOpts {
                cwd: None,
                input: None,
                timeout: Some(Duration::from_secs(30)),
                env: vec![("CLAUDE_CONFIG_DIR".into(), None)],
            },
        ) {
            if out.code != Some(0) {
                logging::warn(
                    "blocked_session_stop_failed",
                    json!({ "session": full, "stderr": truncate(out.stderr.trim(), 120) }),
                );
            }
        }
        anyhow::bail!(
            "phiên mở ra nhưng KẸT ngay ở hộp thoại duyệt MCP của dự án (workspace có .mcp.json: project-agent, vault) — nó chờ một phím bấm mà điện thoại không gõ được, nên đã dừng lại. Cách gỡ, làm MỘT LẦN cho mỗi dự án trên máy: cd {} && claude  →  Enter (duyệt) hoặc Esc (bỏ hết), rồi thoát. Sau đó /new chạy được.",
            dir.display()
        );
    }

    Ok(Started {
        session_id: full,
        project: project.to_string(),
        cwd: dir.to_string_lossy().to_string(),
        task: task.to_string(),
        ts: crate::logging::now_iso(),
    })
}

/// The id `claude stop` accepts — the SHORT one.
///
/// `claude agents` reports both: `id` is 8 characters, `sessionId` is the full
/// uuid. `stop` only matches the short form and answers a full uuid with
/// *"No job matching '…'. Run 'claude agents' to list running sessions."* —
/// which hub logged as a warning while telling the owner the session had
/// stopped. Everything else here keys on the full id, so the narrowing happens
/// at the one call that needs it.
fn short_id(session_id: &str) -> &str {
    session_id.split('-').next().unwrap_or(session_id)
}

/// Stop a background session. Its conversation is kept, so it can be continued.
pub fn stop_background(cfg: &Config, session: &LiveSession) -> Result<()> {
    if session.kind != "background" {
        // An interactive session belongs to whoever opened the terminal. Hà
        // decided on 2026-08-08 that hub only ever drives what hub started.
        anyhow::bail!(
            "chỉ dừng được phiên do hub mở (phiên này là {})",
            session.kind
        );
    }
    let out = run(
        &cfg.claude_cli,
        &["stop", short_id(&session.session_id)],
        RunOpts {
            cwd: None,
            input: None,
            timeout: Some(Duration::from_secs(60)),
            env: vec![(
                "CLAUDE_CONFIG_DIR".into(),
                account_dir(cfg, &session.account),
            )],
        },
    )?;
    if out.code != Some(0) {
        anyhow::bail!(
            "claude exit {:?}: {}",
            out.code,
            truncate(
                if out.stderr.trim().is_empty() {
                    &out.stdout
                } else {
                    &out.stderr
                },
                200
            )
        );
    }
    Ok(())
}

/// What one turn added to a session that was continued in place.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Told {
    pub session_id: String,
    pub source_name: String,
    pub text: String,
    pub answer: String,
    /// See `Handover::cost_usd` — recorded, never published.
    #[serde(default, skip_serializing)]
    pub cost_usd: f64,
    pub ts: String,
}

/// Continue a session IN PLACE — a real next turn, not an aside (UC-S05).
///
/// The wall here is the CLI's, not a policy hub invented: resuming a live
/// background agent is refused outright —
/// *"Session … is currently running as a background agent (bg). Use `claude
/// agents` to find and attach to it, or add --fork-session to branch off a
/// copy."* So "talk into a session while it works" has no path at all from a
/// phone; `attach` needs a terminal on the machine, and forking is a different
/// thing (UC-S05b level 2, which hub already offers).
///
/// What DOES work, measured 2026-08-08: stop the agent first, then resume. The
/// session id stays the same and the transcript grows (8434 → 11529 bytes,
/// 16 → 22 records) — a genuine next turn on the same thread.
pub fn tell(cfg: &Config, session: &LiveSession, text: &str) -> Result<Told> {
    let text = text.trim();
    if text.is_empty() {
        anyhow::bail!("chưa có nội dung");
    }
    if session.kind != "background" {
        anyhow::bail!(
            "chỉ nói tiếp được vào phiên do hub mở. Phiên này mở từ terminal/VS Code — dùng \"hỏi bên lề\" để hỏi mà không đụng vào nó."
        );
    }
    if session.status.as_deref() == Some("busy") {
        anyhow::bail!(
            "phiên đang chạy dở nên claude không cho nối vào. Dừng nó trước (nút Dừng), hoặc dùng \"hỏi bên lề\" để hỏi mà không cắt việc."
        );
    }

    let estimate = fork_cost_estimate(cfg, session);
    let cap = (estimate * 2.0).max(cfg.call.max_budget_usd).to_string();
    let cwd = crate::config::expand_home(Path::new(&session.cwd));
    // Same denylist the session was started with: continuing a task must not
    // quietly hand it powers its first turn did not have.
    let mut args: Vec<&str> = vec!["-p", "--resume", &session.session_id, "--disallowedTools"];
    args.extend_from_slice(&DENIED_TOOLS);
    args.extend_from_slice(&["--max-budget-usd", &cap, "--output-format", "json"]);
    let out = run(
        &cfg.claude_cli,
        &args,
        RunOpts {
            cwd: cwd.is_dir().then_some(cwd.as_path()),
            input: Some(text.to_string()),
            timeout: Some(Duration::from_secs(cfg.call.timeout_sec)),
            env: vec![(
                "CLAUDE_CONFIG_DIR".into(),
                account_dir(cfg, &session.account),
            )],
        },
    )?;
    if out.timed_out {
        anyhow::bail!("quá {}s", cfg.call.timeout_sec);
    }
    if out.code != Some(0) {
        anyhow::bail!(
            "claude exit {:?}: {}",
            out.code,
            truncate(
                if out.stderr.trim().is_empty() {
                    &out.stdout
                } else {
                    &out.stderr
                },
                200
            )
        );
    }
    let v: Value = serde_json::from_str(&out.stdout)
        .map_err(|e| anyhow::anyhow!("kết quả không đọc được: {e}"))?;
    let cost_usd = v
        .get("total_cost_usd")
        .and_then(|c| c.as_f64())
        .unwrap_or(0.0);
    if v.get("is_error").and_then(Value::as_bool) == Some(true) {
        anyhow::bail!(
            "claude báo lỗi (đã tính ${cost_usd:.4}): {}",
            truncate(
                v.get("result").and_then(|s| s.as_str()).unwrap_or("(rỗng)"),
                200
            )
        );
    }
    let got = v
        .get("session_id")
        .and_then(|s| s.as_str())
        .unwrap_or_default();
    if got != session.session_id {
        // A NEW id means the turn landed somewhere else — the opposite of what
        // this verb promises. Say so instead of reporting a cheerful success on
        // a thread the owner is not looking at.
        anyhow::bail!("lượt này rơi vào phiên khác ({got}) chứ không nối vào phiên cũ");
    }
    Ok(Told {
        session_id: session.session_id.clone(),
        source_name: session.name.clone(),
        text: text.to_string(),
        answer: gate_preview(
            v.get("result")
                .and_then(|s| s.as_str())
                .unwrap_or_default()
                .trim(),
            "[hub ẩn câu trả lời: có thể chứa bí mật — mở phiên trên máy để xem]",
        ),
        cost_usd,
        ts: crate::logging::now_iso(),
    })
}

/// `CLAUDE_CONFIG_DIR` for an account label — `None` means the ambient account.
fn account_dir(cfg: &Config, account: &str) -> Option<String> {
    cfg.claude_accounts_or_ambient()
        .into_iter()
        .find(|a| a.name == account)
        .and_then(|a| a.config_dir)
        .filter(|d| !d.is_empty())
        .map(|d| {
            crate::config::expand_home(Path::new(&d))
                .to_string_lossy()
                .to_string()
        })
}

/// Sessions per account, for a one-line summary.
pub fn count_by_account(snap: &SessionsSnapshot) -> BTreeMap<String, usize> {
    let mut counts = BTreeMap::new();
    for s in &snap.sessions {
        *counts.entry(s.account.clone()).or_insert(0) += 1;
    }
    counts
}
