//! The Claude CLI sessions running on this machine — read-only.
//!
//! This is hub's OTHER job, and the one the owner actually asked for: he runs
//! `claude` in terminals on this Mac and wants to watch and drive that work
//! from a phone. Everything here observes; nothing here starts, stops, or types
//! into a session. Driving comes later and will be its own module, because a
//! read-only view can ship (and be trusted) on its own.
//!
//! Three facts about this machine decided the shape, all measured 2026-08-08:
//!
//!   1. `claude agents --json` lists live sessions WITHOUT needing a TTY, but
//!      only for one account: acc1 had 9, acc2 had 2, acc3 had 3. An account is
//!      selected by `CLAUDE_CONFIG_DIR`, and the default account is selected by
//!      that variable being ABSENT — pointing it at `~/.claude` reports "not
//!      logged in". So: one call per account, and the default account's entry
//!      must clear the variable rather than set it.
//!   2. Transcripts live at `<transcript_root>/projects/<slug>/<id>.jsonl` and
//!      are appended live. On this machine acc2/acc3 symlink `projects` back to
//!      acc1, so one root covers all three.
//!   3. `cwd` is NOT the project: all 14 live sessions were started from
//!      `~/Documents/projects`, the parent folder. The session NAME is what
//!      carries meaning ("Tiếp tục dwork"), and `projects-87` is autogenerated.

use std::collections::BTreeMap;
use std::io::{Read, Seek, SeekFrom};
use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::Result;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use crate::config::{ClaudeAccountCfg, Config};
use crate::exec::{run, truncate, RunOpts};
use crate::logging;

/// How much of the tail of a transcript to read. Transcripts reach 12 MB; the
/// last conversational turn is always within a few hundred KB of the end, and
/// reading the whole file 14 times per cycle would be the expensive way to
/// learn the same thing.
const TAIL_BYTES: u64 = 256 * 1024;
const PREVIEW_CHARS: usize = 240;
const LIST_TIMEOUT: Duration = Duration::from_secs(30);

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LiveSession {
    /// Which account owns it — the label from config, not a credential.
    pub account: String,
    pub session_id: String,
    /// Autogenerated ("projects-87") or meaningful ("Tiếp tục dwork").
    pub name: String,
    pub cwd: String,
    /// "interactive" (a terminal / editor) or "background".
    pub kind: String,
    pub pid: i64,
    pub started_at_ms: i64,
    /// Last write to the transcript, RFC3339. `None` = no transcript found.
    pub last_activity: Option<String>,
    /// Role of the last real conversation turn, skipping bookkeeping records.
    pub last_role: Option<String>,
    pub last_text: Option<String>,
    /// Why this row is thinner than the others. Never silently empty.
    pub note: Option<String>,
    /// The permission mode the session is running under ("auto", "dontAsk",
    /// "default"…).
    ///
    /// Measured 2026-08-08 across ~14k records: the transcript records the
    /// MODE and never an individual pending prompt, and every session here runs
    /// `auto` (648) or `dontAsk` (76) — they do not ask. So "show me when it
    /// asks for permission" has nothing to show; what matters on a phone is
    /// knowing a session is running unattended in the first place.
    pub permission_mode: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SessionsSnapshot {
    pub sessions: Vec<LiveSession>,
    /// Per-account problems: CLI missing, not logged in, unparseable output.
    /// An account that failed must not look like an account with no sessions.
    pub notes: Vec<String>,
}

/// `~/Documents/projects` → `-Users-hanguyen-Documents-projects`.
///
/// The rule the CLI uses for its transcript folders: every path separator
/// becomes a dash, including the leading one.
pub fn transcript_slug(cwd: &str) -> String {
    let trimmed = cwd.trim_end_matches('/');
    if trimmed.is_empty() {
        return "-".to_string();
    }
    trimmed.replace('/', "-")
}

pub fn transcript_path(root: &Path, cwd: &str, session_id: &str) -> PathBuf {
    root.join("projects")
        .join(transcript_slug(cwd))
        .join(format!("{session_id}.jsonl"))
}

/// Records that are bookkeeping, not conversation. Observed on real
/// transcripts: `pr-link`, `attachment`, `system`, `last-prompt`,
/// `file-history-snapshot`, `queue-operation`, `ai-title`, `mode`,
/// `permission-mode`. Reading the LAST record and calling it the state gets the
/// answer wrong for 5 of 14 live sessions, which is why this walks backwards.
fn is_conversation(kind: &str) -> bool {
    matches!(kind, "assistant" | "user")
}

/// Plain text out of a message record, whatever shape it arrived in.
fn text_of(record: &Value) -> Option<String> {
    let content = record.get("message")?.get("content")?;
    if let Some(s) = content.as_str() {
        return Some(s.trim().to_string()).filter(|s| !s.is_empty());
    }
    let joined = content
        .as_array()?
        .iter()
        .filter_map(|block| match block.get("type").and_then(|t| t.as_str()) {
            Some("text") => block
                .get("text")
                .and_then(|t| t.as_str())
                .map(str::to_string),
            // A turn that is only tool calls has no text; say what it was doing
            // rather than showing an empty row.
            Some("tool_use") => block
                .get("name")
                .and_then(|n| n.as_str())
                .map(|n| format!("[dùng {n}]")),
            _ => None,
        })
        .collect::<Vec<_>>()
        .join(" ");
    Some(joined.trim().to_string()).filter(|s| !s.is_empty())
}

/// Leak labels that make a preview unsafe to carry off this machine.
///
/// NOT the whole of `redaction::leak_scan`. That gate is tuned for a reply to
/// an outsider, so it also flags `/Users/…` paths, IP addresses and words like
/// "blocker" — true of nearly every line of a development session, which would
/// blank the whole view and teach the owner to ignore it. These three are the
/// ones where being wrong is unrecoverable.
///
/// Not hypothetical: the first real run of `hub sessions` (2026-08-08) printed
/// a session whose latest turn stated a login password in plain text. The CLI
/// runs on the owner's own machine, so that is his business — but the portal
/// snapshot lands in a tfl5 doc on a server, which `redaction.rs` itself counts
/// as leaving the machine.
const SECRET_LABELS: [&str; 4] = [
    "credential_word",
    "credential_word_vi",
    "credential_literal",
    "private_key_block",
];

/// Hits that must suppress a preview, or empty if it is safe to carry.
pub fn preview_risk(text: &str) -> Vec<String> {
    crate::redaction::leak_scan(text, &[])
        .into_iter()
        .filter(|l| SECRET_LABELS.contains(&l.as_str()))
        .collect()
}

#[derive(Debug, Default, PartialEq)]
pub struct TranscriptTail {
    pub last_role: Option<String>,
    pub last_text: Option<String>,
    /// Timestamp carried by the last conversational record, if it has one.
    pub last_ts: Option<String>,
    /// Newest `permission-mode` seen in the window.
    pub permission_mode: Option<String>,
}

/// Walk the tail backwards to the newest real conversation turn.
pub fn parse_tail(tail: &str) -> TranscriptTail {
    let mut out = TranscriptTail::default();
    for line in tail.lines().rev() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let Ok(record) = serde_json::from_str::<Value>(line) else {
            // A partial first line is expected: the tail starts mid-file.
            continue;
        };
        let kind = record.get("type").and_then(|t| t.as_str()).unwrap_or("");
        if kind == "permission-mode" && out.permission_mode.is_none() {
            out.permission_mode = record
                .get("permissionMode")
                .and_then(|m| m.as_str())
                .map(str::to_string);
        }
        if !is_conversation(kind) {
            continue;
        }
        // Newest wins: keep scanning backwards only for what is still missing,
        // never overwrite a turn already found with an older one.
        if out.last_text.is_some() {
            continue;
        }
        out.last_role = record
            .get("message")
            .and_then(|m| m.get("role"))
            .and_then(|r| r.as_str())
            .map(str::to_string)
            .or_else(|| Some(kind.to_string()));
        out.last_text = text_of(&record).map(|t| truncate(&t, PREVIEW_CHARS));
        out.last_ts = record
            .get("timestamp")
            .and_then(|t| t.as_str())
            .map(str::to_string);
        // Stop once BOTH are known: the newest turn and the mode it runs under.
        if out.last_text.is_some() && out.permission_mode.is_some() {
            break;
        }
    }
    out
}

fn read_tail(path: &Path) -> Result<String> {
    let mut file = std::fs::File::open(path)?;
    let len = file.metadata()?.len();
    if len > TAIL_BYTES {
        file.seek(SeekFrom::Start(len - TAIL_BYTES))?;
    }
    let mut buf = Vec::with_capacity(TAIL_BYTES as usize);
    file.read_to_end(&mut buf)?;
    Ok(String::from_utf8_lossy(&buf).to_string())
}

fn mtime_rfc3339(path: &Path) -> Option<String> {
    let modified = std::fs::metadata(path).ok()?.modified().ok()?;
    let ts: chrono::DateTime<chrono::Utc> = modified.into();
    Some(ts.to_rfc3339_opts(chrono::SecondsFormat::Secs, true))
}

/// Ask one account's CLI what it has running.
fn list_account(account: &ClaudeAccountCfg, cli: &str) -> Result<Vec<Value>> {
    // Absent variable = default account. Setting it to ~/.claude reports "not
    // logged in", so the default account MUST clear it, not point at it.
    let env = vec![(
        "CLAUDE_CONFIG_DIR".to_string(),
        account
            .config_dir
            .as_deref()
            .filter(|d| !d.is_empty())
            .map(|d| {
                crate::config::expand_home(Path::new(d))
                    .to_string_lossy()
                    .to_string()
            }),
    )];
    let out = run(
        cli,
        &["agents", "--json"],
        RunOpts {
            timeout: Some(LIST_TIMEOUT),
            env,
            ..Default::default()
        },
    )?;
    if out.timed_out {
        anyhow::bail!("`{cli} agents --json` timed out after {}ms", out.ms);
    }
    if out.code != Some(0) {
        anyhow::bail!(
            "`{cli} agents --json` exit {:?}: {}",
            out.code,
            truncate(
                if out.stderr.trim().is_empty() {
                    &out.stdout
                } else {
                    &out.stderr
                },
                200
            )
        );
    }
    let value: Value = serde_json::from_str(&out.stdout).map_err(|e| {
        anyhow::anyhow!("unparseable JSON: {e}; head={}", truncate(&out.stdout, 200))
    })?;
    Ok(value.as_array().cloned().unwrap_or_default())
}

/// Every live session across every configured account, newest activity first.
pub fn snapshot(cfg: &Config) -> SessionsSnapshot {
    let mut out = SessionsSnapshot::default();
    let root = cfg.claude_transcript_root();

    for account in &cfg.claude_accounts_or_ambient() {
        let raw = match list_account(account, &cfg.claude_cli) {
            Ok(v) => v,
            Err(e) => {
                // An account that failed to answer is NOT an account with zero
                // sessions, and the difference matters on a phone.
                logging::warn(
                    "claude_agents_list_failed",
                    json!({ "account": account.name, "err": e.to_string() }),
                );
                out.notes.push(format!(
                    "{}: {}",
                    account.name,
                    truncate(&e.to_string(), 200)
                ));
                continue;
            }
        };

        for s in raw {
            let cwd = s
                .get("cwd")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string();
            let session_id = s
                .get("sessionId")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string();
            let mut row = LiveSession {
                account: account.name.clone(),
                name: s
                    .get("name")
                    .and_then(|v| v.as_str())
                    .unwrap_or("(không tên)")
                    .to_string(),
                kind: s
                    .get("kind")
                    .and_then(|v| v.as_str())
                    .unwrap_or("unknown")
                    .to_string(),
                pid: s.get("pid").and_then(|v| v.as_i64()).unwrap_or(0),
                started_at_ms: s.get("startedAt").and_then(|v| v.as_i64()).unwrap_or(0),
                last_activity: None,
                last_role: None,
                last_text: None,
                note: None,
                permission_mode: None,
                cwd: cwd.clone(),
                session_id: session_id.clone(),
            };

            if session_id.is_empty() {
                row.note = Some("phiên không có sessionId".into());
                out.sessions.push(row);
                continue;
            }

            let path = transcript_path(&root, &cwd, &session_id);
            if !path.exists() {
                // Seen for real: 1 of 14 sessions had no transcript yet.
                row.note = Some("chưa có nhật ký phiên".into());
                out.sessions.push(row);
                continue;
            }
            row.last_activity = mtime_rfc3339(&path);
            match read_tail(&path) {
                Ok(tail) => {
                    let parsed = parse_tail(&tail);
                    if parsed.last_text.is_none() {
                        row.note = Some("chưa có lượt hội thoại nào đọc được".into());
                    }
                    if let Some(ts) = parsed.last_ts {
                        row.last_activity = Some(ts);
                    }
                    row.permission_mode = parsed.permission_mode.clone();
                    row.last_role = parsed.last_role;
                    // Suppressed HERE, at the source, so no downstream surface
                    // can forget: the snapshot, the portal doc and the phone
                    // all read this struct.
                    row.last_text = match &parsed.last_text {
                        Some(t) => {
                            let risk = preview_risk(t);
                            if risk.is_empty() {
                                parsed.last_text.clone()
                            } else {
                                row.note = Some(format!(
                                    "ẩn phần xem trước: có thể chứa bí mật ({}) — mở phiên trên máy để xem",
                                    risk.join(", ")
                                ));
                                None
                            }
                        }
                        None => None,
                    };
                }
                Err(e) => {
                    logging::warn(
                        "claude_transcript_read_failed",
                        json!({ "path": path.display().to_string(), "err": e.to_string() }),
                    );
                    row.note = Some(format!(
                        "không đọc được nhật ký: {}",
                        truncate(&e.to_string(), 120)
                    ));
                }
            }
            out.sessions.push(row);
        }
    }

    // Newest first: half the live sessions had not moved in 40 hours, so a flat
    // list buries the one being worked on right now.
    out.sessions.sort_by(|a, b| {
        b.last_activity
            .cmp(&a.last_activity)
            .then_with(|| b.started_at_ms.cmp(&a.started_at_ms))
    });
    out
}

/// One thing that happened in a session, in the order it happened.
///
/// This is the unit the phone renders to look like a terminal: a sentence, a
/// command, a command's output, a thought. `kind` is what it was, `text` is
/// what to show, `detail` is the extra line a command needs (its arguments).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct StreamEvent {
    /// "say" · "tool" · "result" · "think"
    pub kind: String,
    /// "user" | "assistant"
    pub role: String,
    pub ts: Option<String>,
    /// Tool name for `tool`, empty otherwise.
    pub name: String,
    pub text: String,
    /// True when the leak gate replaced the text — never a silent blank.
    pub withheld: bool,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SessionStream {
    pub session_id: String,
    pub events: Vec<StreamEvent>,
    /// Events dropped off the front because the window is bounded.
    pub older_hidden: usize,
    pub note: Option<String>,
}

/// How much of a tool's output to carry. A `Bash` result can be a whole test
/// run; the phone needs the shape of it, not all of it.
const RESULT_CHARS: usize = 700;
const SAY_CHARS: usize = 4000;

fn block_text(block: &Value) -> String {
    match block.get("type").and_then(|t| t.as_str()) {
        Some("text") => block
            .get("text")
            .and_then(|t| t.as_str())
            .unwrap_or_default()
            .to_string(),
        Some("thinking") => block
            .get("thinking")
            .and_then(|t| t.as_str())
            .unwrap_or_default()
            .to_string(),
        Some("tool_use") => {
            let input = block
                .get("input")
                .map(|i| i.to_string())
                .unwrap_or_default();
            input
        }
        Some("tool_result") => match block.get("content") {
            Some(Value::String(s)) => s.clone(),
            Some(Value::Array(items)) => items
                .iter()
                .filter_map(|b| b.get("text").and_then(|t| t.as_str()))
                .collect::<Vec<_>>()
                .join("\n"),
            _ => String::new(),
        },
        _ => String::new(),
    }
}

/// Every block becomes an event, and every event passes the leak gate on its
/// OWN text.
///
/// This is where "show it like the terminal" collides with "do not publish
/// secrets": a `tool_result` is the output of a command, which is exactly
/// where keys and env vars surface. Gating only the last turn (what the list
/// screen does) would be useless here.
pub fn parse_stream(tail: &str, limit: usize) -> SessionStream {
    let mut events: Vec<StreamEvent> = vec![];
    for line in tail.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        // The window starts mid-file, so a partial first line is expected.
        let Ok(record) = serde_json::from_str::<Value>(line) else {
            continue;
        };
        let kind = record.get("type").and_then(|t| t.as_str()).unwrap_or("");
        if !is_conversation(kind) {
            continue;
        }
        let ts = record
            .get("timestamp")
            .and_then(|t| t.as_str())
            .map(str::to_string);
        let role = record
            .get("message")
            .and_then(|m| m.get("role"))
            .and_then(|r| r.as_str())
            .unwrap_or(kind)
            .to_string();
        let Some(content) = record.get("message").and_then(|m| m.get("content")) else {
            continue;
        };

        let blocks: Vec<Value> = match content {
            Value::String(s) => vec![json!({ "type": "text", "text": s })],
            Value::Array(a) => a.clone(),
            _ => vec![],
        };

        for block in blocks {
            let (event_kind, name, cap) = match block.get("type").and_then(|t| t.as_str()) {
                Some("text") => ("say", String::new(), SAY_CHARS),
                Some("thinking") => ("think", String::new(), RESULT_CHARS),
                Some("tool_use") => (
                    "tool",
                    block
                        .get("name")
                        .and_then(|n| n.as_str())
                        .unwrap_or("?")
                        .to_string(),
                    RESULT_CHARS,
                ),
                Some("tool_result") => ("result", String::new(), RESULT_CHARS),
                _ => continue,
            };
            let raw = block_text(&block);
            let raw = raw.trim();
            if raw.is_empty() {
                continue;
            }
            let risk = preview_risk(raw);
            events.push(StreamEvent {
                kind: event_kind.to_string(),
                role: role.clone(),
                ts: ts.clone(),
                name,
                text: if risk.is_empty() {
                    truncate(raw, cap)
                } else {
                    format!("[hub ẩn: có thể chứa bí mật ({})]", risk.join(", "))
                },
                withheld: !risk.is_empty(),
            });
        }
    }

    let older_hidden = events.len().saturating_sub(limit);
    if older_hidden > 0 {
        events.drain(..older_hidden);
    }
    SessionStream {
        session_id: String::new(),
        events,
        older_hidden,
        note: None,
    }
}

/// Find a session's transcript without knowing its `cwd`.
///
/// The follow loop only has an id: it must not pay for three `claude agents`
/// calls every couple of seconds just to rebuild a path. Transcript folders are
/// shallow, so one readdir per project folder is cheap — and this also survives
/// a session whose `cwd` the caller got wrong.
pub fn find_transcript(root: &Path, session_id: &str) -> Option<PathBuf> {
    let file = format!("{session_id}.jsonl");
    let projects = root.join("projects");
    let dirs = std::fs::read_dir(&projects).ok()?;
    for entry in dirs.flatten() {
        let candidate = entry.path().join(&file);
        if candidate.exists() {
            return Some(candidate);
        }
    }
    None
}

/// When the transcript last changed — the signal the follow loop watches.
pub fn transcript_mtime(path: &Path) -> Option<std::time::SystemTime> {
    std::fs::metadata(path).ok()?.modified().ok()
}

/// The recent stream of one session, ready to render.
pub fn stream(cfg: &Config, session_id: &str, cwd: &str, limit: usize) -> SessionStream {
    let mut out = SessionStream {
        session_id: session_id.to_string(),
        ..Default::default()
    };
    let root = cfg.claude_transcript_root();
    let by_cwd = transcript_path(&root, cwd, session_id);
    let path = if by_cwd.exists() {
        by_cwd
    } else {
        match find_transcript(&root, session_id) {
            Some(p) => p,
            None => {
                out.note = Some("chưa có nhật ký phiên".into());
                return out;
            }
        }
    };
    match read_tail(&path) {
        Ok(tail) => {
            let parsed = parse_stream(&tail, limit);
            out.events = parsed.events;
            out.older_hidden = parsed.older_hidden;
            if out.events.is_empty() {
                out.note = Some("chưa có lượt hội thoại nào đọc được".into());
            }
        }
        Err(e) => {
            logging::warn(
                "claude_transcript_read_failed",
                json!({ "path": path.display().to_string(), "err": e.to_string() }),
            );
            out.note = Some(format!(
                "không đọc được nhật ký: {}",
                truncate(&e.to_string(), 120)
            ));
        }
    }
    out
}

/// A closing note for a session, plus the id that continues its thread.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Handover {
    pub source_id: String,
    pub source_name: String,
    /// The session that carries the work forward. Different from `source_id`.
    pub new_session_id: String,
    pub checkpoint: String,
    pub cost_usd: f64,
    pub ts: String,
    /// How to pick the thread up on the machine.
    pub resume_command: String,
}

const HANDOVER_PROMPT: &str = "\
Phiên này sắp được đóng lại để mở một phiên mới làm tiếp. Viết BÀN GIAO ngắn gọn \
bằng tiếng Việt cho người sẽ tiếp quản, đúng 4 mục, không quá 200 từ:\n\
1. Đang làm gì (mục tiêu của phiên)\n\
2. Đã xong tới đâu — nêu file:dòng hoặc lệnh cụ thể, không nói chung chung\n\
3. Đang dở cái gì, kẹt ở đâu\n\
4. Việc kế tiếp nên làm ngay\n\
Chỉ viết bàn giao. Không chạy công cụ, không sửa file.";

/// Ask a session to write its own handover, on a FORK.
///
/// Fork, not resume-in-place: the original transcript is left byte-identical
/// (verified 2026-08-08 — 15222 bytes before and after), so closing the books
/// can never damage the thread it is describing. The new id is what continues
/// the work.
pub fn handover(cfg: &Config, session: &LiveSession) -> Result<Handover> {
    // Cap the CALL, not just the day. `--resume` loads the whole conversation,
    // so one handover on a 986 KB session cost **$1.72** on its first real run
    // (2026-08-08) — the daily ceiling only refuses the NEXT call, so a single
    // unbounded one blew a $3 day to $4.51. The per-call cap is what makes this
    // path safe to expose on a button.
    let per_call = cfg.triage.max_budget_usd.to_string();
    let out = run(
        &cfg.claude_cli,
        &[
            "-p",
            "--resume",
            &session.session_id,
            "--fork-session",
            "--max-budget-usd",
            &per_call,
            "--output-format",
            "json",
        ],
        RunOpts {
            input: Some(HANDOVER_PROMPT.to_string()),
            timeout: Some(Duration::from_secs(cfg.triage.timeout_sec)),
            env: vec![(
                "CLAUDE_CONFIG_DIR".into(),
                account_dir(cfg, &session.account),
            )],
            ..Default::default()
        },
    )?;
    if out.timed_out {
        anyhow::bail!("bàn giao quá {}s", cfg.triage.timeout_sec);
    }
    if out.code != Some(0) {
        anyhow::bail!(
            "claude exit {:?}: {}",
            out.code,
            truncate(
                if out.stderr.trim().is_empty() {
                    &out.stdout
                } else {
                    &out.stderr
                },
                200
            )
        );
    }
    let v: Value = serde_json::from_str(&out.stdout)
        .map_err(|e| anyhow::anyhow!("kết quả không đọc được: {e}"))?;
    let new_id = v
        .get("session_id")
        .and_then(|s| s.as_str())
        .unwrap_or_default()
        .to_string();
    if new_id.is_empty() || new_id == session.session_id {
        // Without a NEW id there is nothing to continue into, and writing back
        // into the live session is exactly what fork exists to avoid.
        anyhow::bail!("không nhận được session id mới (nhận: {new_id:?})");
    }
    let checkpoint = v
        .get("result")
        .and_then(|s| s.as_str())
        .unwrap_or_default()
        .trim()
        .to_string();
    Ok(Handover {
        source_id: session.session_id.clone(),
        source_name: session.name.clone(),
        new_session_id: new_id.clone(),
        // The handover text is a session talking about its own work, so it can
        // quote anything the session saw — same gate as every other preview.
        checkpoint: if preview_risk(&checkpoint).is_empty() {
            checkpoint
        } else {
            "[hub ẩn bàn giao: có thể chứa bí mật — mở phiên trên máy để xem]".into()
        },
        cost_usd: v
            .get("total_cost_usd")
            .and_then(|c| c.as_f64())
            .unwrap_or(0.0),
        ts: crate::logging::now_iso(),
        resume_command: format!("cd {} && claude --resume {}", session.cwd, new_id),
    })
}

/// `CLAUDE_CONFIG_DIR` for an account label — `None` means the ambient account.
fn account_dir(cfg: &Config, account: &str) -> Option<String> {
    cfg.claude_accounts_or_ambient()
        .into_iter()
        .find(|a| a.name == account)
        .and_then(|a| a.config_dir)
        .filter(|d| !d.is_empty())
        .map(|d| {
            crate::config::expand_home(Path::new(&d))
                .to_string_lossy()
                .to_string()
        })
}

/// Sessions per account, for a one-line summary.
pub fn count_by_account(snap: &SessionsSnapshot) -> BTreeMap<String, usize> {
    let mut counts = BTreeMap::new();
    for s in &snap.sessions {
        *counts.entry(s.account.clone()).or_insert(0) += 1;
    }
    counts
}
